version: '3.8'

services:

  db:
    build: ./postgres
    container_name: db_tripkaro
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_tripkaro
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: on-failure

volumes:
  postgres_data:
